imports:
    - { resource: '../../src/Shared/config/twig.yaml' }
    - { resource: '../../src/App/config/twig.yaml' }

twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
