name: Symfony Certification

services:
    php:
        container_name: sc_php
        build: .docker/php
        image: symfony-certification-php
        volumes:
            - ./:/usr/src
            - ./.docker/php/sc-php.ini:/usr/local/etc/php/conf.d/sc-php.ini
            - ./var/docker/php:/tmp/sc/php
        working_dir: /usr/src
        restart: no
        stdin_open: true
        tty: true
        ports:
            - '8000:8000'
        networks:
            - network

networks:
    network:
        name: sc_network
