services:
    _defaults:
        autowire: false
        autoconfigure: false

    SymfonyCertification\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
