services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    SymfonyCertification\App\Controller\LuckyNumberController:
        arguments:
            - '@twig'
