sc_app:
    resource: ../src/Controller
    type: attribute
    trailing_slash_on_root: false

sc_app_localized:
    resource: ../src/Controller/Localized
    type: attribute
    trailing_slash_on_root: false
    prefix:
        en: ''
        pl: '/pl'
